// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwIuM2km3XfQTYqYpHHpkrXgUGNLNFho',
    appId: '1:864890282522:web:167912c92b623f32e2a7a3',
    messagingSenderId: '864890282522',
    projectId: 'chat-app-94708',
    authDomain: 'chat-app-94708.firebaseapp.com',
    storageBucket: 'chat-app-94708.appspot.com',
    measurementId: 'G-ZT21NV5B47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKc1eIw_g7810WzkXDcdQjF5RJogwwBU',
    appId: '1:864890282522:android:561b54d4bea36fcbe2a7a3',
    messagingSenderId: '864890282522',
    projectId: 'chat-app-94708',
    storageBucket: 'chat-app-94708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXA8rtWVBpg5GtOZ7VueHTwiCGsGkqHDc',
    appId: '1:864890282522:ios:ab8bd9abcecf6cfee2a7a3',
    messagingSenderId: '864890282522',
    projectId: 'chat-app-94708',
    storageBucket: 'chat-app-94708.appspot.com',
    iosClientId: '864890282522-damuaqieam53mj217sh7tm2s6m7lagms.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXA8rtWVBpg5GtOZ7VueHTwiCGsGkqHDc',
    appId: '1:864890282522:ios:ab8bd9abcecf6cfee2a7a3',
    messagingSenderId: '864890282522',
    projectId: 'chat-app-94708',
    storageBucket: 'chat-app-94708.appspot.com',
    iosClientId: '864890282522-damuaqieam53mj217sh7tm2s6m7lagms.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
